sweep:
  name: "test_medium"
  description: "Medium functional test"
  scenario: "config/scenarios/1shinkansen_mount3antenna_3bs.yaml"
  variables:
    - name: "synchronized_antenna_yaw"
      targets:
        - entity_role: "rx"
          field: "antennas.*.relative_rpy[2]"
          unit: "degree"
          range:
            start: -90.0
            end: 90.0
            step: 45.0
    - name: "rx_y_position"
      target:
        entity_role: "rx"
        field: "pose[1]"
      values: [3.0, 5.0]
  execution:
    num_runs: 1
    task_timeout_sec: 600
    real_time_factor: 5.0
